- name: Deploying ec2 instances
  hosts: all
  gather_facts: False
  vars_files:
    - vars.yml

  tasks:
    - name: Provision a set of instances
      ec2:
        key_name: "{{ aws.key_name }}"
        group_id: "{{ aws.group_id }}"
        region: "{{ aws.region }}"
        vpc_subnet_id: "{{ aws.vpc_subnet_id }}"
        instance_type: "{{ aws.instance_type }}"
        instance_profile_name: "{{ aws.instance_profile_name }}"
        image: "{{ aws.image }}"
        count: "{{ aws.count }}"
        assign_public_ip: "{{ aws.assign_public_ip }}"
        instance_tags: "{{ aws.instance_tags }}"
